config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
  resource :user
  resource :session
  resources :login, only: [:index]

  delete 'login' => 'login#destroy'

  post 'rental/:id/' => 'cat_rental_requests#approve_or_deny'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :color, inclusion: { in: %w( Brown Black White ) }
  validates :sex, inclusion: { in: %w( M F ) }

  validates :birth_date, :color, :sex, :name, presence: true

  has_many :cat_rental_requests, dependent: :destroy

  belongs_to :user
  
  def age
    Date.time.now - self.birth_date
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  after_initialize do |request|
    request.status ||= 'PENDING'

  end

  validates :status, inclusion: { in: %w( PENDING APPROVED DENIED ) }
  validate :validate_no_cat_date_overlap

  belongs_to :cat
  belongs_to(
    :requester,
    class_name: "User",
    foreign_key: :requester_id
  )
  has_one :owner, through: :cat, source: :user

  def approve!
    ActiveRecord::Base.transaction do
      self.status = "APPROVED"
      overlapping_requests.each do |request|
        request.deny! unless request.id == self.id
      end

      self.save
    end
  end

  def deny!
    @status = "DENIED"
    self.update(status: "DENIED")
  end

  # private

  def validate_no_cat_date_overlap
    unless status == 'PENDING' || status == 'DENIED'
      if overlapping_approved_requests
        errors[:base] << 'Schedule conflict!'
      end
    end
  end

  def overlapping_requests
    self.class.where("cat_id = #{self.cat_id} AND id NOT NULL").find_all do |cat_request|
      self.start_date < cat_request.end_date && self.end_date > cat_request.start_date
    end
  end

  def overlapping_approved_requests
    overlapping_requests.any? { |cat_request| cat_request.status == 'APPROVED' }
  end
end

app/models/login.rb
class Login < ActiveRecord::Base
  validates :user_id, presence: true
  validates :token, uniqueness: true, presence: true

  belongs_to :user

  def self.find_all_logins_for_user(user)
    Login.where(user_id: user.id)
  end

end

# @user_currently_logged_in_question = Login.find_by(user_info)
# if @user_currently_logged_in_question
#
# else

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :user_name, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize do |user|
    user.session_token ||= create_session_token
  end

  has_many :cats
  has_many :logins

  def create_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user_instance = User.find_by(user_name: user_name)
    if user_instance.is_password?(password)
      return user_instance
    end

    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    login_info = Login.find_by(token: session[:session_token])
    if login_info
      login_info.user
    else
      nil
    end
  end

  def create_session_token
    SecureRandom.urlsafe_base64
  end

  def login_user!
    @user = User.find_by_credentials(params[:user][:user_name],
                                     params[:user][:password])
    if @user
      new_token = create_session_token
      session[:session_token] = new_token
      userid = @user.id
      user_info = {user_id: userid, token: new_token}
      Login.create(user_info)

      redirect_to cats_path
    else
      render :new
    end
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :check_rental_owner, only:[:approve_or_deny]

  def check_rental_owner
    @rental = CatRentalRequest.find(params[:id])
    if @rental.owner != current_user
      redirect_to cats_url
    end
  end

  def index
    @rentals = CatRentalRequest.all

    render :index
  end

  def new
    @rental = CatRentalRequest.new
    @cats = Cat.all

    render :new
  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    @rental.requester_id = current_user.id
    @rental.save

    redirect_to cat_rental_request_url(@rental)
  end

  def show
    @rental = CatRentalRequest.find(params[:id])

    render :show
  end

  def approve_or_deny
    new_status = params[:new_status]
    if new_status == "Approve"
      @rental.approve!
    elsif new_status == "Deny"
      @rental.deny!
    end

    render :show
  end

  private

  def rental_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :check_cat_owner, only: [:edit, :update]

  def check_cat_owner
    @cat = Cat.find(params[:id])
    if @cat.user != current_user
      redirect_to cats_url
    end
  end

  def index
    @cats = Cat.all

    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    @cat.save

    redirect_to cat_url(@cat)
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def edit
    render :edit
  end

  def update
    @cat.update(cat_params)

    redirect_to cat_url(@cat)
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @logins = Login.find_all_logins_for_user(current_user)

    render :index
  end

  def destroy
    @logins = Login.find_all_logins_for_user(current_user)
    id = params[:login][:unique_id]
    user_id = current_user.id

    Login.where(user_id: user_id, id: id).destroy_all

    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged_in, only: [:new, :create]

  def already_logged_in
    if current_user
      redirect_to cats_url
    end
  end

  def new
    @user = User.new

    render :new
  end

  def create
    login_user!
  end

  def destroy
    @user = current_user
    userid = @user.id
    Login.where(user_id: userid, token: session[:session_token]).destroy_all
    session[:session_token] = nil
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in, only: [:new, :create]

  def already_logged_in
    if current_user
      redirect_to cats_url
    end
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/index.html.erb
<h3>All Rental Requests</h3>
<% @rentals.each do |rental| %>
  <ul>
    <li> <%= rental.start_date %></li>
    <li> <%= rental.end_date %></li>
  </ul>
<% end %>

app/views/cat_rental_requests/new.html.erb
<h3>Rent A Cat !</h3>

<form action="/cat_rental_requests/" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <label for="cat"> Cat: </label>
  <select name="cat_rental_request[cat_id]" id="cat">
    <option value=''></option>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select><br>

  <label for="rental_start"> Start date: </label>
  <input name="cat_rental_request[start_date]" id="rental_start" type="date" value="<%= @rental.start_date %>"><br>
  <label for="rental_end"> End date: </label>
  <input name="cat_rental_request[end_date]" id="rental_end" type="date" value="<%= @rental.end_date %>"><br>

  <input type='submit' values="Request Rental!">
</form>

app/views/cat_rental_requests/show.html.erb
<h3> Cat Rental Request </h3>

<ul>
  <li>Cat: <%= @rental.cat.name %> </li>
  <li>Start date: <%= @rental.start_date %> </li>
  <li>End date: <%= @rental.end_date %> </li>
  <li>Status: <%= @rental.status %> </li>
</ul>

app/views/cats/_form.html.erb
<form action="/cats/<%= @cat.id %>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <% if cat.persisted? %>
    <input name="_method" type="hidden" value="patch">
  <% end %>

  <label for="cat_name"> Name: </label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>" ><br>

  <label for="cat_birthday"> Birthday: </label>
  <input name="cat[birth_date]" id="cat_birthday" type="date" value="<%= @cat.birth_date %>"><br>

  <label for="cat_color"> Color: </label>
  <select name="cat[color]" id="cat_color">

    <option value=''></option>
    <option value="Black" <%= 'selected=selected' if @cat.color == 'Black'%>>Black</option>
    <option value="Brown" <%= 'selected=selected' if @cat.color == 'Brown'%>>Brown</option>
    <option value="White" <%= 'selected=selected' if @cat.color == 'White'%>>White</option>
  </select><br>

  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
  <%= 'checked=checked' if @cat.sex == 'M'%>>
  <label for="cat_sex_male"> Male </label><br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
  <%= 'checked=checked' if @cat.sex == 'F'%>>
  <label for="cat_sex_female"> Female </label><br>

  <label for="cat_description">Cat's description</label><br>
  <textarea name="cat[description]" id="cat_description"><%= @cat.description %></textarea><br>
  <input type='submit' values="Create cat!">
</form>

app/views/cats/edit.html.erb
<h2> Edit Cat </h2>
<%= render partial: "form", locals: {cat: @cat}%>

app/views/cats/index.html.erb
<h1> All Cats </h1>

<% @cats.each do |cat| %>
<ul>
  <li> Name: <a href='/cats/<%= cat.id %>'> <%= cat.name %> </a> </li>
</ul>

<% end %>

<a href='/cats/new'> Create new cat! </a>

app/views/cats/new.html.erb
<h2> New Cat </h2>
<%= render partial: "form", locals: {cat: @cat}%>

app/views/cats/show.html.erb
<h1> A Cat </h1>
<p> <%= @cat.name %></p>
<table>
  <tr>
    <th> Color </th>
    <th> Sex </th>
    <th> Birthday </th>
    <th> Description </th>
  </tr>
  <tr>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.sex %></td>
    <td> <%= @cat.birth_date %></td>
    <td> <%= @cat.description %></td>
  </tr>
</table>

<br>
<% @cat.cat_rental_requests.order(:start_date).each do |request|  %>
<ul>
  <li> Start date: <%= request.start_date %> </li>
  <li> End date: <%= request.end_date %> </li>
  <li> Status: <%= request.status %></li>
  <br>
  <% if request.status == 'PENDING' && current_user == request.owner%>
    <form action="/rental/<%= request.id %>" method="post">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <input name="new_status" type='submit' value="Approve">
      <input name="new_status" type='submit' value="Deny">
    </form>
  <% end %>
  <li><%=request.requester.user_name%></li>
</ul>
<% end %>

<a href='/cats/<%= @cat.id %>/edit'>Edit <%= @cat.name %></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <p>Hello <%= current_user.user_name.capitalize %></p>
  <%= button_to "Logout", session_url, method: :delete %>
<% else %>
<p><%= button_to "Login", new_session_url, method: :get %> </p>

<% end %>
<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<ul>
<% @logins.each do |login| %>

  <li> <%= login.updated_at %></li>
  <li> Log me out of this session </li>
  <form id="form_id" action="login" method="post">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <input name="_method" type="hidden" value="delete">
    <input type="hidden" name="login[unique_id]" value="<%= login.id %>">
    <input type='submit' values="Log out">
  </form>
  <br>

<% end %>
</ul>

app/views/users/new.html.erb
<h3>Create a new user</h3>
<form action="/user" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <label for="user_name">Username:</label>
  <input type="text" name="user[user_name]" value="<%= @user.user_name %>" id="user_name">

  <label for="password">Password:</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit" value="Log In">
</form>

app/views/users/show.html.erb
<h3>Hello <%=@user.user_name%></h3>